### ISSUE TITLE
Protobuf in ue5

### ISSUE THREAD

**Issue by henning998** [FuryGamesPtyLtd/Tasmania#1]
Where do you place the generated files from the proto compiler, I keep getting a lot of errors like:

libprotobuf.lib(extension_set_heavy.cc.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort

I have figured out that if I place the generated files from the proto compiler in the include folder of the plugin I can include the generated file, but when I try to set up a message in c++ I get the following error:

error LNK2019: unresolved external symbol "protected: __cdecl tutorial::Person::Person(class google::protobuf::Arena *,bool)" (??0Person@tutorial@@IEAA@PEAVArena@protobuf@google@@_N@Z) referenced in function "public: __cdecl AMyActor::AMyActor(void)" (??0AMyActor@@QEAA@XZ)
1>MyActor.cpp.obj : error LNK2019: unresolved external symbol "const tutorial::Person::`vftable'" (??_7Person@tutorial@@6B@) referenced in function "public: __cdecl AMyActor::AMyActor(void)" (??0AMyActor@@QEAA@XZ)

I have tried testing the protobuf library in a c++ program, where it worked fine.

**Comment by tomazos** [comment]
We've created a demo unreal project called Victor at https://github.com/FuryGamesPtyLtd/Victor that shows how to integrate Tasmania and serialize and deserialize a protobuf.  Let us know if it works for you.

**Comment by henning998** [comment]
I have cloned your project and both Wakefield and Tasmania but i still gets  a lot LNK2001 error like it can't find the library.
The problem seems to come from when it tries to build Hobart

1>libprotobuf.lib(dynamic_message.cc.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort
1>libprotobuf.lib(map_field.cc.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort
1>libprotobuf.lib(reflection_ops.cc.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort
1>libprotobuf.lib(extension_set_heavy.cc.obj) : error LNK2001: unresolved external symbol __std_init_once_link_alternate_names_and_abort


Also what version of unreal engine and visual studio are you using?

**Comment by tomazos** [comment]
Unreal Engine 5.0.3 and Visual Studio 2022

**Comment by tomazos** [comment]
The script we used to build the windows version is under `Tasmania\Source\GoogleProtocolBuffers\Build.bat` maybe try the cmake command from that Build.bat to build your own version of libprotobuf.lib and see if that works better.   (Looks like it might be some compatibility issue with Visual Studio: https://github.com/conan-io/conan/issues/11260)

**Comment by henning998** [comment]
I found a solution to the problem

1.  Follow the guide on [Protobuf](https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md) to build the library, **BUT make sure to set** when getting to the **CMake Configuration**
 `-Dprotobuf_MSVC_STATIC_RUNTIME=OFF -Dprotobuf_DISABLE_RTTI=ON`
3.  Change the protobuf.lib in the plugin out with your newly built protobuf.lib
4.  When building for the first time you will get a lot of errors, but more importantly, it will create a Binaries folder in your unreal project folder
5. You need to take a copy of the protobuf.lib and place it in the \Binaries\ [platform]  ex: `\Binaries\Win64` when using Windows

I hope this will help someone
